---
apiVersion: v1
kind: Service
metadata:
    labels:
        name: local-zipkin-elasticsearch
    name: local-zipkin-elasticsearch
spec:
    type: NodePort
    ports:
        - port: 9200
          protocol: TCP
          targetPort: 9200
          nodePort: 31101
    selector:
        app: local-zipkin-elasticsearch
