# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|


  config.vm.provision "shell", path: "bootstrap_nfs.sh"

  # Kubernetes Master Server
  config.vm.define "nfs-server" do |nfs_server|
    nfs_server.vm.box = "centos/7"
    nfs_server.vm.hostname = "nfs-server.example.com"
    nfs_server.vm.network "private_network", ip: "172.42.42.200"
    nfs_server.vm.provider "virtualbox" do |v|
      v.name = "nfs-server"
      v.memory = 1024
      v.cpus = 1
    end
  end
end
