---
apiVersion: v1
kind: Service
metadata:
    labels:
        name: local-zipkin-ui
    name: local-zipkin-ui
spec:
    type: NodePort
    ports:
        - port: 9411
          protocol: TCP
          targetPort: 9411
          nodePort: 31102
    selector:
        app: local-zipkin-ui
