# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  # config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define "kmaster" do |kmaster|
    kmaster.vm.box = "centos/7"
    kmaster.vm.hostname = "kmaster.example.com"
    kmaster.vm.network "private_network", ip: "172.42.42.100"
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "kmaster"
      v.memory = 2048
      v.cpus = 2
    end
    kmaster.vm.provision "shell", path: "bootstrap.sh"
    # kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh"
    kmaster.vm.provision "shell", path: "bootstrap_kmaster_calico.sh"
  end

  NodeCount = 1

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "kworker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "kworker#{i}.example.com"
      workernode.vm.network "private_network", ip: "172.42.42.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "kworker#{i}"
        v.memory = 4024
        v.cpus = 4
      end
      workernode.vm.provision "shell", path: "bootstrap.sh"
      workernode.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
  end



  config.vm.define "nfs-server" do |nfs_server|
    nfs_server.vm.box = "centos/7"
    nfs_server.vm.hostname = "nfs-server.example.com"
    nfs_server.vm.network "private_network", ip: "172.42.42.200"
    nfs_server.vm.provider "virtualbox" do |v|
      v.name = "nfs-server"
      v.memory = 1024
      v.cpus = 1
    end
    nfs_server.vm.provision "shell", path: "bootstrap_nfs.sh"
  end


end
