apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-resource
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  rules:
    - host: jenkins.example.com
      http:
        paths:
          - backend:
              serviceName: jenkins
              servicePort: 8080
